services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: airatoemoncms
        volumes:
          - /etc/localtime:/etc/localtime:ro  # Mount host's localtime (read-only)
          - ./config:/config:ro # Mount config directory (read-only)
          - ./logs:/logs  # Mount logs directory
          - /var/run/dbus/:/var/run/dbus/:z # Needed for dbus access (BLE)
        environment:
            - AIRATOEMONCMS_LOGLEVEL=INFO  # Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        command: python airatoemoncms.py 
        privileged: true
        restart: "always"
