services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: airatoemoncms_app
        volumes:
          - /etc/localtime:/etc/localtime:ro  # Mount host's localtime (read-only)
          - /var/run/dbus/:/var/run/dbus/:z
        environment:
            - AIRA_UUID=xxx # populate with Aira Heat Pump UUID
            - AIRA_DHW_TARGET_TEMP=55 # populate with DHW target temp as configured in Aira app
            - EMONCMS_UPLOAD_MAXRETRIES=5 # before restarting the container
            - EMONCMS_UPLOAD_WAITTIME=5 # time between BLE reads (in seconds) excluding time to read and post data
            - EMONCMS_URL=https://emoncms.org/input/post
            - EMONCMS_APIKEY=xxx # populate with your EmonCMS write API key
            - EMONCMS_NODE=AiraHeatPump
        command: python airatoemoncms.py 
        privileged: true
        restart: "always"

